# Generated by Django 3.1.2 on 2020-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201002_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timetables',
            field=models.CharField(default='9h', max_length=200),
            preserve_default=False,
        ),
    ]
